[[models]]
name = "insults_data"
url = "http://files.deeppavlov.ai/datasets/insults_data.tar.gz?config=insults_kaggle_conv_bert"

[[models]]
name = "conversational_cased"
url = "http://files.deeppavlov.ai/deeppavlov_data/bert/conversational_cased_L-12_H-768_A-12.tar.gz?config=insults_kaggle_conv_bert"

[[models]]
name = "insults_kaggle_v4"
url = "http://files.deeppavlov.ai/deeppavlov_data/classifiers/insults_kaggle_v4.tar.gz?config=insults_kaggle_conv_bert"