[[models]]
name = "insults_data"
url = "https://github.com/aidmodels/insult_detection/releases/download/v0.1/insults_data.tar.gz"

[[models]]
name = "conversational_cased"
url = "https://github.com/aidmodels/insult_detection/releases/download/v0.1/conversational_cased_L-12_H-768_A-12.tar.gz"

[[models]]
name = "insults_kaggle_v4"
url = "https://github.com/aidmodels/insult_detection/releases/download/v0.1/insults_kaggle_v4.tar.gz"